spring:
  application:
    name: fitness-backend
  
  profiles:
    active: ${SPRING_PROFILE:dev}
  
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/fitness_db}
      auto-index-creation: true
  
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  
  cache:
    type: redis
    redis:
      time-to-live: 600000
      cache-null-values: false

server:
  port: ${PORT:8080}
  error:
    include-message: always
    include-binding-errors: always
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  expiration: 86400000 # 24 hours
  refresh-expiration: 604800000 # 7 days

# AI Model Service URLs
ai:
  services:
    workout-recommender:
      url: ${WORKOUT_SERVICE_URL:http://localhost:8001}
      timeout: 30000
    nutrition-planner:
      url: ${NUTRITION_SERVICE_URL:http://localhost:8002}
      timeout: 30000
    pose-checker:
      url: ${POSE_SERVICE_URL:http://localhost:8003}
      timeout: 60000
    chatbot:
      url: ${CHATBOT_SERVICE_URL:http://localhost:8004}
      timeout: 30000

# AWS S3 Configuration (optional)
aws:
  s3:
    enabled: ${S3_ENABLED:false}
    access-key: ${AWS_ACCESS_KEY:}
    secret-key: ${AWS_SECRET_KEY:}
    region: ${AWS_REGION:us-east-1}
    bucket-name: ${S3_BUCKET_NAME:fitness-app-storage}

# CORS Configuration
cors:
  allowed-origins: ${CORS_ORIGINS:http://localhost:3000,http://localhost:5173}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
  allowed-headers: "*"
  allow-credentials: true
  max-age: 3600

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
  show-actuator: true

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  health:
    mongo:
      enabled: true
    redis:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

# Logging Configuration
logging:
  level:
    root: INFO
    com.aifitness.backend: DEBUG
    org.springframework.security: DEBUG
    org.springframework.data.mongodb: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/fitness-backend.log
    max-size: 10MB
    max-history: 30